import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid w-1/4 justify-center ">
          <h1>Login</h1>
          <input
            className="shadow-md border"
            placeholder="username"
            type="text"
          />
          <input
            className="shadow-md border"
            placeholder="password"
            type="text"
          />
          <Link href={"/profile"}>login</Link>
        </div>
      </main>
    </>
  );
}
